In [1]:
import pandas as pd
import datetime as dt
import numpy as np
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect, extract
from sqlalchemy import Column, Integer, Float, Date, String, VARCHAR, Boolean, ForeignKey
from sqlalchemy.ext.declarative import declarative_base

In [2]:
# data = '../Excels/dailyActivity_merged.csv'
# data2 = '../Excels/dailyCalories_merged.csv'
# data3 = '../Excels/dailyIntensities_merged.csv'
# data4 = '../Excels/dailySteps_merged.csv'
# data5 = '../Excels/heartrate_seconds_merged.csv'
# data6 = '../Excels/hourlyCalories_merged.csv'
# data7 = '../Excels/hourlyIntensities_merged.csv'
# data8 = '../Excels/hourlySteps_merged.csv'
# data9 = '../Excels/minuteCaloriesNarrow_merged.csv'
# data10 = '../Excels/minuteCaloriesWide_merged.csv'
# data11 = '../Excels/minuteIntensitiesNarrow_merged.csv'
# data12 = '../Excels/minuteIntensitiesWide_merged.csv'
# data13 = '../Excels/minuteMETsNarrow_merged.csv'
# data14 = '../Excels/minuteSleep_merged.csv'
# data15 = '../Excels/minuteStepsNarrow_merged.csv'
# data16 = '../Excels/minuteStepsWide_merged.csv'
# data17 = '../Excels/sleepDay_merged.csv'
# data18 = '../Excels/weightLogInfo_merged.csv'

In [3]:
def toDf(data):
    df = pd.read_csv(data)
    return df

In [5]:
df = toDf(data)
df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories
0,1503960366,4/12/2016,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985
1,1503960366,4/13/2016,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797
2,1503960366,4/14/2016,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776
3,1503960366,4/15/2016,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745
4,1503960366,4/16/2016,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863

In [7]:
Base = declarative_base()

In [ ]:
class dailyActivity(Base):
    __tablename__= 'dailyActivity'
    index = Column(VARCHAR, primary_key=True)
    Id = Column(VARCHAR)
    ActivityDate = Column(VARCHAR)
    TotalSteps = Column(Integer)
    TotalDistance = Column(Integer)
    TrackerDistance = Column(Integer)
    LoggedActivitiesDistance = Column(Integer)
    VeryActiveDistance = Column(Integer)
    ModeratelyActiveDistance = Column(Integer)
    LightActiveDistance = Column(Integer)
    SedentaryActiveDistance = Column(Integer)
    VeryActiveMinutes = Column(Integer)

In [ ]:
# engine = create_engine("sqlite:///olympics_db.sqlite")
# conn = engine.connect()
# Base.metadata.create_all(engine)

# session = Session(bind=engine)